name: CodeCov

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Generate report
      run: |
        pip install coverage
        cd test
        coverage run testSym.py
        coverage run testBigNum.py
        coverage run testNum.py
        coverage run testCsv.py
        coverage report testSym.py
        coverage report testBigNum.py
        coverage report testNum.py
        coverage report testCsv.py
        coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
