# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: HW2 Test Cases

on:
  push:
    branches: [ "main", "lua" ]
  pull_request:
    branches: [ "main", "lua" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: HW2 - Testing Sym
      run: |
        cd test
        python testSym.py

    - name: Hw2 - Testing Num
      run: |
        cd test
        python testNum.py
      
    - name: Hw2 - Testing BigNum
      run: |
        cd test
        python testBigNum.py
